- name: Mikrotik DNS sync
  gather_facts: no
  hosts: localhost
  vars:
    username: "admin"
    hosts:
      - host: "sw1.dacha.vs"
        network_id: "1"
        self_id: "1"
        subnets:
          - name: "management"
          - name: "LAN"
          - name: "WAN"
          - name: "guest"
          - name: "marina"

  vars_prompt:
    - name: password
      private: true

  tasks:
    # Default settings for all
    - name: "Disable IPv6"
      community.routeros.api_modify:
        hostname: "{{ item.host }}"
        password: "{{ password }}"
        username: "{{ username }}"
        path: "ipv6 settings"
        data:
          - disable-ipv6: yes
      loop: "{{ hosts }}"

    - name: "Enable dns server handle external requests"
      community.routeros.api_modify:
        hostname: "{{ item.host }}"
        password: "{{ password }}"
        username: "{{ username }}"
        path: "ip dns"
        data:
          - allow-remote-requests: yes
      loop: "{{ hosts }}"

    - name: "Set time-zone-name to Europe/Moscow"
      community.routeros.api_modify:
        hostname: "{{ item.host }}"
        password: "{{ password }}"
        username: "{{ username }}"
        path: "system clock"
        data:
          - time-zone-name: "Europe/Moscow"
      loop: "{{ hosts }}"

    - name: "Create net bridges"
      community.routeros.api_modify:
        hostname: "{{ item.0.host }}"
        password: "{{ password }}"
        username: "{{ username }}"
        path: "interface bridge"
        data:
          - name: "{{ item.1.name }}-bridge"
      with_subelements:
        - "{{ hosts }}"
        - "subnets"

#    - name: "Set address for management-bridge"
#      community.routeros.api_modify:
#        hostname: "{{ item.host }}"
#        password: "{{ password }}"
#        username: "{{ username }}"
#        path: "ip address"
#        data:
#          - address: "10.{{ item.network_id }}.255.{{ item.self_id }}/24"
#            network: "10.{{ item.network_id }}.255.0"
#            interface: "management-bridge"
#      loop: "{{ hosts }}"
