- name: Mikrotik DNS sync
  gather_facts: no
  hosts: localhost
  vars:
    username: "admin"
    hosts:
      - "sw1.rack.vs"
      - "sw1.dacha.vs"
      - "sw2.dacha.vs"

  vars_prompt:
    - name: password
      private: true

  tasks:
    - name: "Sync DNS records"
      community.routeros.api_modify:
        hostname: "{{ item }}"
        password: "{{ password }}"
        username: "{{ username }}"
        handle_entries_content: remove
        handle_absent_entries: remove
        path: "ip dns static"
        data:
          # Regular hosts
          - name: "pve1.vs"
            address: "10.100.0.10"

          - name: "pve2.vs"
            address: "10.100.0.20"

          - name: "ca.vs"
            address: "10.100.0.21"

          - name: "zoneminder.vs"
            address: "10.100.0.12"

          # Test hosts
          - name: "pve1.test.vs"
            address: "10.100.1.10"

          - name: "ca.test.vs"
            address: "10.100.1.11"

          - name: "zoneminder.test.vs"
            address: "10.100.1.15"

          # Routers
          - name: "sw1.rack.vs"
            address: "10.100.255.1"

          - name: "sw1.dacha.vs"
            address: "10.1.255.1"

          - name: "sw2.dacha.vs"
            address: "10.1.255.2"
      loop: "{{ hosts }}"